import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopNav from "@/components/ReUsableComponents/TopNav";

// Load Plus Jakarta Sans Font
const jakarta = localFont({
  src: [
    {
      path: "../fonts/PlusJakartaSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/PlusJakartaSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/PlusJakartaSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-jakarta",
});

const instrumentSerif = localFont({
  src: [
    {
      path: "../fonts/InstrumentSerif-Italic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-instrument",
});
// Metadata for SEO
export const metadata: Metadata = {
  title: "Adinn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable} ${instrumentSerif.variable} antialiased`}
      >
         <div className="absolute top-0 left-0 w-full z-50">
            <TopNav />
          </div>

        
        {children}
      </body>
    </html>
  );
}
