import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopNav from "@/components/reusable-components/TopNav";
import "bootstrap-icons/font/bootstrap-icons.css";
import { GoogleAnalytics } from "@next/third-parties/google";

// Load Plus Jakarta Sans Font
const jakarta = localFont({
  src: [
    {
      path: "../fonts/PlusJakartaSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/PlusJakartaSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/PlusJakartaSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-jakarta",
});

const instrumentSerif = localFont({
  src: [
    {
      path: "../fonts/InstrumentSerif-Italic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-instrument",
});
// Metadata for SEO
export const metadata: Metadata = {
  title: "Adinn",
  description: "Generated by create next app",
  verification: {
    google: "ZCG_8p_9edjm1fYQvR7CxQQBU1EAhvbpksSXtRuDzqo",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <!-- Seo meta tags  --> */}
        {/* <!-- Google tag (gtag.js) --> */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-G93WCBJ8NN"></script>
        <script>
          {
            `
   window.dataLayer = window.dataLayer || [];
  function gtag(){ dataLayer.push(arguments); }
  gtag('js', new Date());

  gtag('config', 'G-G93WCBJ8NN');
  `
          }
        </script>
{/* Meta Pixel code  */}
{/* <!-- Meta Pixel Code --> */}
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '932648620811419');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=932648620811419&ev=PageView&noscript=1"
/></noscript>
{/* <!-- End Meta Pixel Code --> */}
        {/* Microsoft Clarity */}
        <script type="text/javascript">
          {

            `
     (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "vi9xm8je8s");
    `
          }
        </script>

      </head>
      <body
        className={`${jakarta.variable} ${instrumentSerif.variable} antialiased`}
      >
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-PPQPSGN3"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>

        <div className="absolute top-0 left-0 w-full z-50">
          <TopNav />
        </div>


        {children}
      </body>
    </html>
  );
}
